name: IntelRegion

on:
  push:
    branches: [main]
  
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Upgrade dependencies
        run: |
          pip install django-environ cryptography Django djangorestframework djangorestframework-simplejwt drf-nested-routers model-bakery pytest-django

      - name: Testing with Pytest
        run: |
          pytest
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}